networks:
  devnetwork:

services:
  migrate:
    build:
      context: .
      dockerfile: backend/Dockerfile
    working_dir: /app/backend
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
    command: sh -c "npm install && npx knex migrate:latest --knexfile=./src/knexFile.ts --env $NODE_ENV"
    depends_on:
      - db
    networks:
      - devnetwork

