version: "3.8"

services:
  app:
    image: 909500381447.dkr.ecr.us-east-1.amazonaws.com/interview-prep:latest
    ports:
      - "80:80"
    depends_on:
      - json-server

  json-server:
    image: clue/json-server
    ports:
      - "3000:3000"
    volumes:
      - ./db.json:/data/db.json
    command: json-server --watch /data/db.json --port 3000
